#!/usr/bin/env python3
from lxml import html
from gi.repository import Gio
import requests
#import urllib2
import os
import urllib.request
#import wget 

url = 'http://www.reddit.com/r/spaceporn'
request = urllib.request.Request(url)
request.add_header('user-agent', 'mintpaper/0.0.1')

page = requests.get(url)
tree = html.fromstring(page.text)
print(page)
print(tree)

image = tree.xpath('//p[@class="title"]/a/@href')
print(image)
#wget.download(image[1])
urllib.request.urlretrieve(image[1])
settings = Gio.Settings.new("org.cinnamon.desktop.background")
settings.set_string("picture-uri", "file://home/daniemxli/wallpaper/" + image[1])

#gsettings set org.cinnamon.desktop.background picture-uri

