#!/usr/bin/env python
from lxml import html
from gi.repository import Gio
import requests
import urllib2
import urllib
import wget 

url = 'http://www.reddit.com/r/spaceporn'
request = urllib2.Request(url)
request.add_header('User-Agent', 'Mozilla 3.10')

page = requests.get(url)
tree = html.fromstring(page.text)


image = tree.xpath('//p[@class="title"]/a/@href')
print(image)
wget.download(image[1])
settings = Gio.Settings.new("org.cinnamon.desktop.background")
settings.set_string("picture-uri", "file:///home/daniemxli/wallpaper/" + image[1])

#gsettings set org.cinnamon.desktop.background picture-uri

